apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-detr-aug1-test1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-detr-aug1-test1 
  name: test-detr-aug1-test1
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: test-detr-aug1-test1 
